def scaleNm(nm):
    match nm:
        case "pm":
            return 1e3
        case "nm":
            return 1e1
        case "um":
            return 1e-3
        case "mm":
            return 1e-6
        case "m":
            return 1e-9